---
# file: ./vsc/tasks/main.yml

- block:

  - name: visual studio code install extension
    raw: "code --install-extension {{ item }}"
    with_items: '{{ extensions }}'
    changed_when: no

  tags:
    - vsc