---
# file: ./fonts/tasks/main.yml

- block:

  - name: Download ricty
    get_url:
      url: http://www.rs.tus.ac.jp/yyusa/ricty_diminished/ricty_diminished-4.1.1.tar.gz
      dest: ~/Downloads/ricty_diminished-4.1.1.tar.gz

  - name: Unzip ricty
    raw: tar zxvf ~/Downloads/ricty_diminished-4.1.1.tar.gz -C ~/Library/Fonts/

  tags:
    - fonts